### PR TITLE
Graph Plotter

### PR DESCRIPTION
**Pull request by PPraneesh**
# Pull Request: Add Graph Plotting Program in C

**Description:**

Hello maintainers!

I'm excited to submit this pull request, which adds a simple Graph Plotting program in C to the repository. This program allows users to visualize quadratic equations in the form of `y = ax^2 + bx + c` by generating an ASCII art representation of the graph.

**Changes Made:**

- Added a new C program for graph plotting.
- The program prompts the user to input coefficients (a, b, c) for a quadratic equation.
- It then calculates and displays an ASCII art representation of the quadratic graph.

**How to Use:**

- Compile the program using a C compiler (e.g., gcc).
- Run the compiled program.
- Enter the coefficients (a, b, c) when prompted.
- The program will display the graph of the corresponding quadratic equation.

**Screenshots/Visuals:**

Screeshot of the output

**Checklist:**

- [x] I have tested the program to ensure it works as intended.
- [x] There are no linting errors or warnings.

**Additional Information:**

This program is intended to be a beginner-friendly tool for visualizing quadratic equations. Users can easily understand and interact with it to explore the behavior of quadratic functions.

Thank you for considering my contribution! I look forward to your feedback and suggestions for improvement.

Best regards,
Praneesh

### CODE REVIEW

**Comment by PPraneesh** [comment]
Would you kindly consider adding the label 'hacktoberfest-accepted' to this pull request if you find the code acceptable? Your assistance with this would be highly valued.

**Comment by WinTer1165** [comment]
main.c works fine

**Comment by PPraneesh** [comment]
Can you please add the label 'hactoberfest-accepted' ? 
It would be helpful.

**Comment by WinTer1165** [comment]
Ok will do!

**Comment by PPraneesh** [comment]
Thank you so much 
Just add it to this pull request.

**Pull request merged**
